# 1 stage
FROM openjdk:21-jdk as builder
WORKDIR app
ARG JAR_FILE=build/libs/health-1.0-SNAPSHOT.jar
COPY ${JAR_FILE} health.jar
RUN java -Djarmode=layertools -jar health.jar extract

# 2 stage
FROM openjdk:21-jdk
WORKDIR app
COPY --from=builder app/dependencies/ ./
COPY --from=builder app/spring-boot-loader/ ./
COPY --from=builder app/snapshot-dependencies/ ./
COPY --from=builder app/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]